# Generated by Django 3.1.1 on 2020-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_auto_20200920_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='tender_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
