# Generated by Django 3.1.1 on 2020-10-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
